services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: ./node_modules/.bin/nodemon server.js
  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - server
  stun:
    image: coturn/coturn
    ports:
      - "3478:3478/udp" # STUN port
      - "3478:3478/tcp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    command:
      --log-file=stdout
