version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: ./node_modules/.bin/nodemon server.js
  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - server